/**
 * 130+ unique Pokémon TCG cards — real set/number IDs for pokemontcg.io CDN hires images.
 * Primary source: Scarlet & Violet "151" set (sv3pt5) + premium V/ex full-arts from SWSH/SV.
 */

const { enrichCard } = require("./card-meta");
const { lookupDexNumber } = require("./pokemon-dex");

const PRICE = {
  Common: [0.15, 1.5],
  Uncommon: [0.5, 4],
  Rare: [3, 18],
  "Rare Holo": [8, 45],
  "Rare Holo V": [12, 85],
  "Rare Holo VMAX": [25, 130],
  "Rare Holo ex": [15, 95],
  "Double Rare": [10, 60],
  "Ultra Rare": [35, 180],
  "Illustration Rare": [40, 220],
  "Special Illustration Rare": [80, 400],
  "Hyper Rare": [90, 450],
  "Rare Secret": [60, 350],
};

function priceFor(rarity) {
  const [min, max] = PRICE[rarity] || [2, 20];
  return Math.round((min + Math.random() * (max - min)) * 100) / 100;
}

function img(setId, num) {
  const raw = String(num).trim();
  const n = /^\d+$/.test(raw) ? String(parseInt(raw, 10)) : raw;
  return {
    imageUrl: `https://images.pokemontcg.io/${setId}/${n}.png`,
    imageUrlLarge: `https://images.pokemontcg.io/${setId}/${n}_hires.png`,
  };
}

// Gen 1 — Pokémon 151 set (sv3pt5), one unique species per card
const SV151 = [
  [1, "Bulbasaur", 70, "Grass", "Common"],
  [2, "Ivysaur", 100, "Grass", "Uncommon"],
  [3, "Venusaur ex", 340, "Grass", "Double Rare"],
  [4, "Charmander", 70, "Fire", "Common"],
  [5, "Charmeleon", 90, "Fire", "Uncommon"],
  [6, "Charizard ex", 330, "Fire", "Double Rare"],
  [7, "Squirtle", 70, "Water", "Common"],
  [8, "Wartortle", 100, "Water", "Uncommon"],
  [9, "Blastoise ex", 330, "Water", "Double Rare"],
  [10, "Caterpie", 50, "Grass", "Common"],
  [11, "Metapod", 80, "Grass", "Common"],
  [12, "Butterfree", 120, "Grass", "Uncommon"],
  [13, "Weedle", 50, "Grass", "Common"],
  [14, "Kakuna", 80, "Grass", "Common"],
  [15, "Beedrill", 130, "Grass", "Uncommon"],
  [16, "Pidgey", 50, "Colorless", "Common"],
  [17, "Pidgeotto", 90, "Colorless", "Uncommon"],
  [18, "Pidgeot ex", 280, "Colorless", "Double Rare"],
  [19, "Rattata", 40, "Colorless", "Common"],
  [20, "Raticate", 90, "Colorless", "Common"],
  [21, "Spearow", 60, "Colorless", "Common"],
  [22, "Fearow", 110, "Colorless", "Uncommon"],
  [23, "Ekans", 70, "Darkness", "Common"],
  [24, "Arbok ex", 270, "Darkness", "Double Rare"],
  [25, "Pikachu", 70, "Lightning", "Common"],
  [26, "Raichu", 120, "Lightning", "Rare"],
  [27, "Sandshrew", 70, "Fighting", "Common"],
  [28, "Sandslash", 120, "Fighting", "Uncommon"],
  [29, "Nidoran♀", 60, "Darkness", "Common"],
  [30, "Nidorina", 90, "Darkness", "Uncommon"],
  [31, "Nidoqueen", 140, "Darkness", "Rare"],
  [32, "Nidoran♂", 60, "Darkness", "Common"],
  [33, "Nidorino", 90, "Darkness", "Uncommon"],
  [34, "Nidoking", 140, "Darkness", "Rare"],
  [35, "Clefairy", 60, "Psychic", "Common"],
  [36, "Clefable ex", 260, "Psychic", "Double Rare"],
  [37, "Vulpix", 70, "Fire", "Common"],
  [38, "Ninetales ex", 280, "Fire", "Double Rare"],
  [39, "Jigglypuff", 70, "Colorless", "Common"],
  [40, "Wigglytuff ex", 250, "Colorless", "Double Rare"],
  [41, "Zubat", 50, "Darkness", "Common"],
  [42, "Golbat", 90, "Darkness", "Common"],
  [43, "Oddish", 70, "Grass", "Common"],
  [44, "Gloom", 90, "Grass", "Common"],
  [45, "Vileplume", 140, "Grass", "Uncommon"],
  [46, "Paras", 70, "Grass", "Common"],
  [47, "Parasect", 120, "Grass", "Uncommon"],
  [48, "Venonat", 60, "Grass", "Common"],
  [49, "Venomoth", 110, "Grass", "Uncommon"],
  [50, "Diglett", 50, "Fighting", "Common"],
  [51, "Dugtrio", 90, "Fighting", "Uncommon"],
  [52, "Meowth", 60, "Colorless", "Common"],
  [53, "Persian", 110, "Colorless", "Uncommon"],
  [54, "Psyduck", 70, "Water", "Common"],
  [55, "Golduck", 120, "Water", "Uncommon"],
  [56, "Mankey", 60, "Fighting", "Common"],
  [57, "Primeape", 120, "Fighting", "Uncommon"],
  [58, "Growlithe", 80, "Fire", "Common"],
  [59, "Arcanine", 130, "Fire", "Rare"],
  [60, "Poliwag", 60, "Water", "Common"],
  [61, "Poliwhirl", 90, "Water", "Common"],
  [62, "Poliwrath", 140, "Water", "Rare"],
  [63, "Abra", 50, "Psychic", "Common"],
  [64, "Kadabra", 80, "Psychic", "Uncommon"],
  [65, "Alakazam ex", 310, "Psychic", "Double Rare"],
  [66, "Machop", 70, "Fighting", "Common"],
  [67, "Machoke", 100, "Fighting", "Uncommon"],
  [68, "Machamp", 150, "Fighting", "Rare"],
  [69, "Bellsprout", 60, "Grass", "Common"],
  [70, "Weepinbell", 90, "Grass", "Common"],
  [71, "Victreebel", 140, "Grass", "Uncommon"],
  [72, "Tentacool", 60, "Water", "Common"],
  [73, "Tentacruel", 120, "Water", "Uncommon"],
  [74, "Geodude", 70, "Fighting", "Common"],
  [75, "Graveler", 110, "Fighting", "Common"],
  [76, "Golem ex", 300, "Fighting", "Double Rare"],
  [77, "Ponyta", 70, "Fire", "Common"],
  [78, "Rapidash", 120, "Fire", "Uncommon"],
  [79, "Slowpoke", 80, "Psychic", "Common"],
  [80, "Slowbro", 130, "Psychic", "Uncommon"],
  [81, "Magnemite", 60, "Lightning", "Common"],
  [82, "Magneton", 100, "Lightning", "Uncommon"],
  [83, "Farfetch'd", 90, "Colorless", "Common"],
  [84, "Doduo", 70, "Colorless", "Common"],
  [85, "Dodrio", 110, "Colorless", "Uncommon"],
  [86, "Seel", 80, "Water", "Common"],
  [87, "Dewgong", 130, "Water", "Uncommon"],
  [88, "Grimer", 80, "Darkness", "Common"],
  [89, "Muk", 140, "Darkness", "Uncommon"],
  [90, "Shellder", 70, "Water", "Common"],
  [91, "Cloyster", 130, "Water", "Uncommon"],
  [92, "Gastly", 50, "Psychic", "Common"],
  [93, "Haunter", 80, "Psychic", "Common"],
  [94, "Gengar", 130, "Psychic", "Rare"],
  [95, "Onix", 120, "Fighting", "Uncommon"],
  [96, "Drowzee", 70, "Psychic", "Common"],
  [97, "Hypno", 110, "Psychic", "Uncommon"],
  [98, "Krabby", 70, "Water", "Common"],
  [99, "Kingler", 130, "Water", "Uncommon"],
  [100, "Voltorb", 60, "Lightning", "Common"],
  [101, "Electrode", 100, "Lightning", "Uncommon"],
  [102, "Exeggcute", 50, "Grass", "Common"],
  [103, "Exeggutor", 140, "Grass", "Uncommon"],
  [104, "Cubone", 70, "Fighting", "Common"],
  [105, "Marowak", 120, "Fighting", "Uncommon"],
  [106, "Hitmonlee", 130, "Fighting", "Rare"],
  [107, "Hitmonchan", 130, "Fighting", "Rare"],
  [108, "Lickitung", 100, "Colorless", "Common"],
  [109, "Koffing", 70, "Darkness", "Common"],
  [110, "Weezing", 120, "Darkness", "Uncommon"],
  [111, "Rhyhorn", 100, "Fighting", "Common"],
  [112, "Rhydon", 140, "Fighting", "Uncommon"],
  [113, "Chansey", 120, "Colorless", "Rare"],
  [114, "Tangela", 80, "Grass", "Common"],
  [115, "Kangaskhan", 130, "Colorless", "Rare"],
  [116, "Horsea", 60, "Water", "Common"],
  [117, "Seadra", 100, "Water", "Uncommon"],
  [118, "Goldeen", 70, "Water", "Common"],
  [119, "Seaking", 110, "Water", "Uncommon"],
  [120, "Staryu", 60, "Water", "Common"],
  [121, "Starmie", 90, "Water", "Uncommon"],
  [122, "Mr. Mime", 80, "Psychic", "Common"],
  [123, "Scyther", 100, "Grass", "Uncommon"],
  [124, "Jynx", 90, "Psychic", "Uncommon"],
  [125, "Electabuzz", 110, "Lightning", "Uncommon"],
  [126, "Magmar", 110, "Fire", "Uncommon"],
  [127, "Pinsir", 120, "Grass", "Uncommon"],
  [128, "Tauros", 120, "Colorless", "Uncommon"],
  [129, "Magikarp", 30, "Water", "Common"],
  [130, "Gyarados", 150, "Water", "Rare"],
];

// Premium full-art V / ex cards (like the Mewtwo V example)
const PREMIUM_FULLART = [
  { setId: "swsh45", num: "58", name: "Mewtwo V", hp: 220, type: "Psychic", rarity: "Rare Holo V", setName: "Mewtwo V-UNION", artist: "PLANETA Mochizuki" },
  { setId: "xy11", num: "123", name: "Gyarados EX", hp: 180, type: "Water", rarity: "Rare Holo EX", setName: "Steam Siege", artist: "Mitsuhiro Arita" },
  { setId: "swsh4", num: "79", name: "Charizard V", hp: 220, type: "Fire", rarity: "Rare Holo V", setName: "Vivid Voltage", artist: "5ban Graphics" },
  { setId: "swsh4", num: "170", name: "Charizard VMAX", hp: 330, type: "Fire", rarity: "Rare Holo VMAX", setName: "Vivid Voltage", artist: "5ban Graphics" },
  { setId: "swsh3", num: "20", name: "Blastoise V", hp: 220, type: "Water", rarity: "Rare Holo V", setName: "Darkness Ablaze", artist: "5ban Graphics" },
  { setId: "swsh2", num: "17", name: "Venusaur V", hp: 220, type: "Grass", rarity: "Rare Holo V", setName: "Rebel Clash", artist: "5ban Graphics" },
  { setId: "swsh1", num: "44", name: "Pikachu V", hp: 190, type: "Lightning", rarity: "Rare Holo V", setName: "Sword & Shield", artist: "5ban Graphics" },
  { setId: "swsh1", num: "170", name: "Pikachu VMAX", hp: 310, type: "Lightning", rarity: "Rare Holo VMAX", setName: "Sword & Shield", artist: "5ban Graphics" },
  { setId: "swsh12", num: "46", name: "Lugia V", hp: 220, type: "Colorless", rarity: "Rare Holo V", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "186", name: "Lugia VSTAR", hp: 280, type: "Colorless", rarity: "Rare Holo VSTAR", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh11", num: "46", name: "Rayquaza VMAX", hp: 320, type: "Dragon", rarity: "Rare Holo VMAX", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh8", num: "20", name: "Gengar VMAX", hp: 320, type: "Psychic", rarity: "Rare Holo VMAX", setName: "Fusion Strike", artist: "5ban Graphics" },
  { setId: "swsh7", num: "24", name: "Umbreon VMAX", hp: 310, type: "Darkness", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh7", num: "25", name: "Espeon VMAX", hp: 310, type: "Psychic", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh7", num: "196", name: "Rayquaza V", hp: 210, type: "Dragon", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "sv4", num: "54", name: "Charizard ex", hp: 330, type: "Fire", rarity: "Double Rare", setName: "Paradox Rift", artist: "akira komayama" },
  { setId: "sv4", num: "205", name: "Garchomp ex", hp: 320, type: "Fighting", rarity: "Ultra Rare", setName: "Paradox Rift", artist: "5ban Graphics" },
  { setId: "sv3", num: "86", name: "Gardevoir ex", hp: 310, type: "Psychic", rarity: "Double Rare", setName: "Obsidian Flames", artist: "5ban Graphics" },
  { setId: "sv1", num: "228", name: "Miraidon ex", hp: 330, type: "Lightning", rarity: "Special Illustration Rare", setName: "Scarlet & Violet", artist: "akira komayama" },
  { setId: "sv1", num: "229", name: "Koraidon ex", hp: 330, type: "Fighting", rarity: "Special Illustration Rare", setName: "Scarlet & Violet", artist: "akira komayama" },
  { setId: "sv3pt5", num: "151", name: "Mew ex", hp: 180, type: "Psychic", rarity: "Double Rare", setName: "151", artist: "aky CG Works" },
  { setId: "sv3pt5", num: "150", name: "Mewtwo", hp: 130, type: "Psychic", rarity: "Rare", setName: "151", artist: "Teeziro" },
  { setId: "sv3pt5", num: "149", name: "Dragonite", hp: 160, type: "Colorless", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "148", name: "Dragonair", hp: 100, type: "Dragon", rarity: "Uncommon", setName: "151", artist: "Teeziro" },
  { setId: "sv3pt5", num: "147", name: "Dratini", hp: 70, type: "Dragon", rarity: "Common", setName: "151", artist: "Teeziro" },
  { setId: "sv3pt5", num: "146", name: "Moltres", hp: 120, type: "Fire", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "145", name: "Zapdos", hp: 120, type: "Lightning", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "144", name: "Articuno", hp: 120, type: "Water", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "143", name: "Snorlax", hp: 160, type: "Colorless", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "142", name: "Aerodactyl", hp: 130, type: "Colorless", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "141", name: "Kabutops", hp: 140, type: "Fighting", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "140", name: "Kabuto", hp: 90, type: "Fighting", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "139", name: "Omastar", hp: 140, type: "Water", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "138", name: "Omanyte", hp: 90, type: "Water", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "137", name: "Porygon", hp: 80, type: "Colorless", rarity: "Common", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "136", name: "Flareon", hp: 130, type: "Fire", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "135", name: "Jolteon", hp: 110, type: "Lightning", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "134", name: "Vaporeon", hp: 130, type: "Water", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "133", name: "Eevee", hp: 70, type: "Colorless", rarity: "Common", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "132", name: "Ditto", hp: 70, type: "Colorless", rarity: "Rare", setName: "151", artist: "GOSSAN" },
  { setId: "sv3pt5", num: "131", name: "Lapras", hp: 130, type: "Water", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
];

const EXTRA_CARDS = [
  // sv1 (Scarlet & Violet Base Set)
  { setId: "sv1", num: "1", name: "Sprigatito", hp: 70, type: "Grass", rarity: "Common", setName: "Scarlet & Violet", artist: "Kouki Saitou" },
  { setId: "sv1", num: "2", name: "Floragato", hp: 90, type: "Grass", rarity: "Uncommon", setName: "Scarlet & Violet", artist: "Kouki Saitou" },
  { setId: "sv1", num: "3", name: "Meowscarada ex", hp: 310, type: "Grass", rarity: "Double Rare", setName: "Scarlet & Violet", artist: "5ban Graphics" },
  { setId: "sv1", num: "19", name: "Fuecoco", hp: 80, type: "Fire", rarity: "Common", setName: "Scarlet & Violet", artist: "Kouki Saitou" },
  { setId: "sv1", num: "20", name: "Crocalor", hp: 100, type: "Fire", rarity: "Uncommon", setName: "Scarlet & Violet", artist: "Kouki Saitou" },
  { setId: "sv1", num: "21", name: "Skeledirge ex", hp: 340, type: "Fire", rarity: "Double Rare", setName: "Scarlet & Violet", artist: "5ban Graphics" },
  { setId: "sv1", num: "32", name: "Quaxly", hp: 70, type: "Water", rarity: "Common", setName: "Scarlet & Violet", artist: "Kouki Saitou" },
  { setId: "sv1", num: "33", name: "Quaxwell", hp: 90, type: "Water", rarity: "Uncommon", setName: "Scarlet & Violet", artist: "Kouki Saitou" },
  { setId: "sv1", num: "34", name: "Quaquaval ex", hp: 320, type: "Water", rarity: "Double Rare", setName: "Scarlet & Violet", artist: "5ban Graphics" },
  { setId: "sv1", num: "61", name: "Pawmi", hp: 50, type: "Lightning", rarity: "Common", setName: "Scarlet & Violet", artist: "Mizue" },
  { setId: "sv1", num: "62", name: "Pawmo", hp: 80, type: "Lightning", rarity: "Uncommon", setName: "Scarlet & Violet", artist: "Mizue" },
  { setId: "sv1", num: "63", name: "Pawmot", hp: 130, type: "Lightning", rarity: "Rare", setName: "Scarlet & Violet", artist: "Mizue" },
  { setId: "sv1", num: "73", name: "Ralts", hp: 70, type: "Psychic", rarity: "Common", setName: "Scarlet & Violet", artist: "Jiro Sasumo" },
  { setId: "sv1", num: "74", name: "Kirlia", hp: 80, type: "Psychic", rarity: "Uncommon", setName: "Scarlet & Violet", artist: "Jiro Sasumo" },
  { setId: "sv1", num: "80", name: "Dondozo", hp: 160, type: "Water", rarity: "Rare", setName: "Scarlet & Violet", artist: "Kariya" },
  { setId: "sv1", num: "81", name: "Tatsugiri", hp: 70, type: "Water", rarity: "Rare", setName: "Scarlet & Violet", artist: "Kariya" },
  { setId: "sv1", num: "86", name: "Lucario", hp: 130, type: "Fighting", rarity: "Rare", setName: "Scarlet & Violet", artist: "Souichirou Gunjima" },
  { setId: "sv1", num: "113", name: "Varoom", hp: 60, type: "Metal", rarity: "Common", setName: "Scarlet & Violet", artist: "Taira Akitsu" },
  { setId: "sv1", num: "114", name: "Revavroom", hp: 140, type: "Metal", rarity: "Rare", setName: "Scarlet & Violet", artist: "Taira Akitsu" },
  { setId: "sv1", num: "125", name: "Cyclizar", hp: 110, type: "Colorless", rarity: "Common", setName: "Scarlet & Violet", artist: "Nagomi Nijo" },
  { setId: "sv1", num: "151", name: "Koraidon ex", hp: 230, type: "Fighting", rarity: "Double Rare", setName: "Scarlet & Violet", artist: "5ban Graphics" },
  { setId: "sv1", num: "152", name: "Miraidon ex", hp: 220, type: "Lightning", rarity: "Double Rare", setName: "Scarlet & Violet", artist: "5ban Graphics" },

  // sv2 (Paldea Evolved)
  { setId: "sv2", num: "8", name: "Tarountula", hp: 40, type: "Grass", rarity: "Common", setName: "Paldea Evolved", artist: "Teeziro" },
  { setId: "sv2", num: "9", name: "Spidops ex", hp: 260, type: "Grass", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },
  { setId: "sv2", num: "57", name: "Bellibolt ex", hp: 280, type: "Lightning", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },
  { setId: "sv2", num: "74", name: "Pawmot ex", hp: 300, type: "Lightning", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },
  { setId: "sv2", num: "85", name: "Tinkatink", hp: 60, type: "Psychic", rarity: "Common", setName: "Paldea Evolved", artist: "Mizue" },
  { setId: "sv2", num: "86", name: "Tinkatuff", hp: 80, type: "Psychic", rarity: "Uncommon", setName: "Paldea Evolved", artist: "Mizue" },
  { setId: "sv2", num: "87", name: "Tinkaton", hp: 140, type: "Psychic", rarity: "Rare", setName: "Paldea Evolved", artist: "Mizue" },
  { setId: "sv2", num: "123", name: "Noibat", hp: 70, type: "Dragon", rarity: "Common", setName: "Paldea Evolved", artist: "Kouki Saitou" },
  { setId: "sv2", num: "124", name: "Noivern ex", hp: 260, type: "Dragon", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },
  { setId: "sv2", num: "140", name: "Squawkabilly ex", hp: 160, type: "Colorless", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },
  { setId: "sv2", num: "164", name: "Chien-Pao ex", hp: 220, type: "Water", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },
  { setId: "sv2", num: "168", name: "Ting-Lu ex", hp: 240, type: "Fighting", rarity: "Double Rare", setName: "Paldea Evolved", artist: "5ban Graphics" },

  // sv3 (Obsidian Flames)
  { setId: "sv3", num: "1", name: "Oddish", hp: 50, type: "Grass", rarity: "Common", setName: "Obsidian Flames", artist: "Kouki Saitou" },
  { setId: "sv3", num: "2", name: "Gloom", hp: 70, type: "Grass", rarity: "Common", setName: "Obsidian Flames", artist: "Kouki Saitou" },
  { setId: "sv3", num: "3", name: "Bellossom", hp: 130, type: "Grass", rarity: "Rare", setName: "Obsidian Flames", artist: "Kouki Saitou" },
  { setId: "sv3", num: "4", name: "Scyther", hp: 70, type: "Grass", rarity: "Common", setName: "Obsidian Flames", artist: "Souichirou Gunjima" },
  { setId: "sv3", num: "5", name: "Scizor", hp: 140, type: "Metal", rarity: "Rare", setName: "Obsidian Flames", artist: "Souichirou Gunjima" },
  { setId: "sv3", num: "22", name: "Vulpix", hp: 60, type: "Fire", rarity: "Common", setName: "Obsidian Flames", artist: "Teeziro" },
  { setId: "sv3", num: "23", name: "Ninetales", hp: 120, type: "Fire", rarity: "Rare", setName: "Obsidian Flames", artist: "Teeziro" },
  { setId: "sv3", num: "42", name: "Lapras", hp: 110, type: "Water", rarity: "Uncommon", setName: "Obsidian Flames", artist: "Kariya" },
  { setId: "sv3", num: "48", name: "Bellibolt", hp: 140, type: "Lightning", rarity: "Rare", setName: "Obsidian Flames", artist: "Nagomi Nijo" },
  { setId: "sv3", num: "59", name: "Clefairy", hp: 60, type: "Psychic", rarity: "Common", setName: "Obsidian Flames", artist: "Mizue" },
  { setId: "sv3", num: "60", name: "Clefable ex", hp: 260, type: "Psychic", rarity: "Double Rare", setName: "Obsidian Flames", artist: "5ban Graphics" },
  { setId: "sv3", num: "63", name: "Togepi", hp: 50, type: "Psychic", rarity: "Common", setName: "Obsidian Flames", artist: "Jiro Sasumo" },
  { setId: "sv3", num: "64", name: "Togetic", hp: 90, type: "Psychic", rarity: "Uncommon", setName: "Obsidian Flames", artist: "Jiro Sasumo" },
  { setId: "sv3", num: "65", name: "Togekiss", hp: 150, type: "Psychic", rarity: "Rare", setName: "Obsidian Flames", artist: "Jiro Sasumo" },
  { setId: "sv3", num: "79", name: "Umbreon", hp: 110, type: "Darkness", rarity: "Rare", setName: "Obsidian Flames", artist: "Teeziro" },
  { setId: "sv3", num: "125", name: "Charizard ex", hp: 330, type: "Fire", rarity: "Double Rare", setName: "Obsidian Flames", artist: "5ban Graphics" },

  // sv4 (Paradox Rift)
  { setId: "sv4", num: "1", name: "Surskit", hp: 50, type: "Grass", rarity: "Common", setName: "Paradox Rift", artist: "Kouki Saitou" },
  { setId: "sv4", num: "2", name: "Masquerain", hp: 100, type: "Grass", rarity: "Common", setName: "Paradox Rift", artist: "Kouki Saitou" },
  { setId: "sv4", num: "11", name: "Pineco", hp: 60, type: "Grass", rarity: "Common", setName: "Paradox Rift", artist: "Teeziro" },
  { setId: "sv4", num: "16", name: "Gimmighoul", hp: 50, type: "Psychic", rarity: "Common", setName: "Paradox Rift", artist: "Nagomi Nijo" },
  { setId: "sv4", num: "17", name: "Gholdengo ex", hp: 260, type: "Metal", rarity: "Double Rare", setName: "Paradox Rift", artist: "5ban Graphics" },
  { setId: "sv4", num: "19", name: "Volcanion", hp: 130, type: "Fire", rarity: "Rare", setName: "Paradox Rift", artist: "Kariya" },
  { setId: "sv4", num: "27", name: "Horsea", hp: 60, type: "Water", rarity: "Common", setName: "Paradox Rift", artist: "Mizue" },
  { setId: "sv4", num: "28", name: "Seadra", hp: 90, type: "Water", rarity: "Common", setName: "Paradox Rift", artist: "Mizue" },
  { setId: "sv4", num: "29", name: "Kingdra", hp: 150, type: "Water", rarity: "Rare", setName: "Paradox Rift", artist: "Mizue" },
  { setId: "sv4", num: "58", name: "Joltik", hp: 50, type: "Lightning", rarity: "Common", setName: "Paradox Rift", artist: "Taira Akitsu" },
  { setId: "sv4", num: "59", name: "Galvantula", hp: 100, type: "Lightning", rarity: "Common", setName: "Paradox Rift", artist: "Taira Akitsu" },
  { setId: "sv4", num: "66", name: "Natu", hp: 50, type: "Psychic", rarity: "Common", setName: "Paradox Rift", artist: "Jiro Sasumo" },
  { setId: "sv4", num: "67", name: "Xatu", hp: 100, type: "Psychic", rarity: "Uncommon", setName: "Paradox Rift", artist: "Jiro Sasumo" },
  { setId: "sv4", num: "81", name: "Toxtricity ex", hp: 260, type: "Lightning", rarity: "Double Rare", setName: "Paradox Rift", artist: "5ban Graphics" },
  { setId: "sv4", num: "108", name: "Roaring Moon ex", hp: 230, type: "Darkness", rarity: "Double Rare", setName: "Paradox Rift", artist: "5ban Graphics" },
  { setId: "sv4", num: "124", name: "Iron Valiant ex", hp: 220, type: "Psychic", rarity: "Double Rare", setName: "Paradox Rift", artist: "5ban Graphics" },
  { setId: "sv4", num: "143", name: "Aegislash", hp: 150, type: "Metal", rarity: "Rare", setName: "Paradox Rift", artist: "Nagomi Nijo" },

  // swsh12 (Silver Tempest)
  { setId: "swsh12", num: "24", name: "Alolan Vulpix V", hp: 190, type: "Water", rarity: "Rare Holo V", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "25", name: "Alolan Vulpix VSTAR", hp: 240, type: "Water", rarity: "Rare Holo VSTAR", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "65", name: "Regieleki V", hp: 200, type: "Lightning", rarity: "Rare Holo V", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "66", name: "Regieleki VMAX", hp: 320, type: "Lightning", rarity: "Rare Holo VMAX", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "112", name: "Ursaluna V", hp: 230, type: "Fighting", rarity: "Rare Holo V", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "138", name: "Regidrago V", hp: 220, type: "Dragon", rarity: "Rare Holo V", setName: "Silver Tempest", artist: "5ban Graphics" },
  { setId: "swsh12", num: "139", name: "Regidrago VSTAR", hp: 280, type: "Dragon", rarity: "Rare Holo VSTAR", setName: "Silver Tempest", artist: "5ban Graphics" },

  // swsh11 (Lost Origin)
  { setId: "swsh11", num: "58", name: "Kyurem V", hp: 220, type: "Water", rarity: "Rare Holo V", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "59", name: "Kyurem VMAX", hp: 330, type: "Water", rarity: "Rare Holo VMAX", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "79", name: "Enamorus V", hp: 210, type: "Psychic", rarity: "Rare Holo V", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "84", name: "Aerodactyl V", hp: 210, type: "Fighting", rarity: "Rare Holo V", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "85", name: "Aerodactyl VSTAR", hp: 260, type: "Fighting", rarity: "Rare Holo VSTAR", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "103", name: "Drapion V", hp: 210, type: "Darkness", rarity: "Rare Holo V", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "130", name: "Goodra V", hp: 220, type: "Dragon", rarity: "Rare Holo V", setName: "Lost Origin", artist: "5ban Graphics" },
  { setId: "swsh11", num: "131", name: "Goodra VSTAR", hp: 270, type: "Dragon", rarity: "Rare Holo VSTAR", setName: "Lost Origin", artist: "5ban Graphics" },

  // swsh10 (Astral Radiance)
  { setId: "swsh10", num: "18", name: "Hisuian Lilligant V", hp: 200, type: "Grass", rarity: "Rare Holo V", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "19", name: "Hisuian Lilligant VSTAR", hp: 260, type: "Grass", rarity: "Rare Holo VSTAR", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "24", name: "Hisuian Typhlosion V", hp: 210, type: "Psychic", rarity: "Rare Holo V", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "25", name: "Hisuian Typhlosion VSTAR", hp: 270, type: "Psychic", rarity: "Rare Holo VSTAR", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "78", name: "Hisuian Decidueye V", hp: 220, type: "Fighting", rarity: "Rare Holo V", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "79", name: "Hisuian Decidueye VSTAR", hp: 270, type: "Fighting", rarity: "Rare Holo VSTAR", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "101", name: "Hisuian Samurott V", hp: 220, type: "Darkness", rarity: "Rare Holo V", setName: "Astral Radiance", artist: "5ban Graphics" },
  { setId: "swsh10", num: "102", name: "Hisuian Samurott VSTAR", hp: 270, type: "Darkness", rarity: "Rare Holo VSTAR", setName: "Astral Radiance", artist: "5ban Graphics" },

  // swsh09 (Brilliant Stars)
  { setId: "swsh09", num: "17", name: "Shaymin V", hp: 220, type: "Grass", rarity: "Rare Holo V", setName: "Brilliant Stars", artist: "5ban Graphics" },
  { setId: "swsh09", num: "18", name: "Shaymin VSTAR", hp: 250, type: "Grass", rarity: "Rare Holo VSTAR", setName: "Brilliant Stars", artist: "5ban Graphics" },
  { setId: "swsh09", num: "40", name: "Charizard V", hp: 220, type: "Fire", rarity: "Rare Holo V", setName: "Brilliant Stars", artist: "5ban Graphics" },
  { setId: "swsh09", num: "41", name: "Charizard VSTAR", hp: 280, type: "Fire", rarity: "Rare Holo VSTAR", setName: "Brilliant Stars", artist: "5ban Graphics" },
  { setId: "swsh09", num: "122", name: "Arceus V", hp: 220, type: "Colorless", rarity: "Rare Holo V", setName: "Brilliant Stars", artist: "5ban Graphics" },
  { setId: "swsh09", num: "123", name: "Arceus VSTAR", hp: 280, type: "Colorless", rarity: "Rare Holo VSTAR", setName: "Brilliant Stars", artist: "5ban Graphics" },

  // swsh07 (Evolving Skies)
  { setId: "swsh07", num: "16", name: "Leafeon V", hp: 200, type: "Grass", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "17", name: "Leafeon VMAX", hp: 310, type: "Grass", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "28", name: "Flareon V", hp: 210, type: "Fire", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "29", name: "Flareon VMAX", hp: 320, type: "Fire", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "30", name: "Vaporeon V", hp: 210, type: "Water", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "31", name: "Vaporeon VMAX", hp: 320, type: "Water", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "50", name: "Jolteon V", hp: 200, type: "Lightning", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "51", name: "Jolteon VMAX", hp: 300, type: "Lightning", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "64", name: "Espeon V", hp: 200, type: "Psychic", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "94", name: "Umbreon V", hp: 200, type: "Darkness", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "95", name: "Umbreon VMAX", hp: 310, type: "Darkness", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "110", name: "Glaceon V", hp: 200, type: "Water", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "111", name: "Glaceon VMAX", hp: 310, type: "Water", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "122", name: "Sylveon V", hp: 205, type: "Psychic", rarity: "Rare Holo V", setName: "Evolving Skies", artist: "5ban Graphics" },
  { setId: "swsh07", num: "123", name: "Sylveon VMAX", hp: 310, type: "Psychic", rarity: "Rare Holo VMAX", setName: "Evolving Skies", artist: "5ban Graphics" },
];

const REGION_CARDS = [
  // Johto
  { setId: "xy9", num: "1", name: "Chikorita", hp: 60, type: "Grass", rarity: "Common", setName: "BREAKpoint", artist: "Mizue" },
  { setId: "xy9", num: "2", name: "Bayleef", hp: 90, type: "Grass", rarity: "Uncommon", setName: "BREAKpoint", artist: "Mizue" },
  { setId: "xy9", num: "3", name: "Meganium", hp: 150, type: "Grass", rarity: "Rare", setName: "BREAKpoint", artist: "Mizue" },
  { setId: "xy8", num: "18", name: "Cyndaquil", hp: 60, type: "Fire", rarity: "Common", setName: "BREAKthrough", artist: "Mizue" },
  { setId: "xy8", num: "19", name: "Quilava", hp: 80, type: "Fire", rarity: "Uncommon", setName: "BREAKthrough", artist: "Mizue" },
  { setId: "dp2", num: "16", name: "Typhlosion", hp: 120, type: "Fire", rarity: "Rare", setName: "Mysterious Treasures", artist: "Kagemaru Himeno" },
  { setId: "xy4", num: "15", name: "Totodile", hp: 60, type: "Water", rarity: "Common", setName: "Phantom Forces", artist: "5ban Graphics" },
  { setId: "xy4", num: "16", name: "Croconaw", hp: 80, type: "Water", rarity: "Uncommon", setName: "Phantom Forces", artist: "5ban Graphics" },
  { setId: "neo1", num: "4", name: "Feraligatr", hp: 120, type: "Water", rarity: "Rare", setName: "Neo Genesis", artist: "Ken Sugimori" },
  { setId: "neo1", num: "1", name: "Ampharos", hp: 100, type: "Lightning", rarity: "Rare", setName: "Neo Genesis", artist: "Ken Sugimori" },
  { setId: "neo2", num: "12", name: "Tyranitar", hp: 140, type: "Darkness", rarity: "Rare", setName: "Neo Discovery", artist: "Ken Sugimori" },
  { setId: "xy1", num: "4", name: "Heracross", hp: 100, type: "Grass", rarity: "Rare", setName: "XY", artist: "Masakazu Fukuda" },
  { setId: "cel25", num: "1", name: "Ho-Oh", hp: 130, type: "Fire", rarity: "Rare", setName: "Celebrations", artist: "Kouki Saitou" },
  { setId: "pop5", num: "2", name: "Lugia", hp: 100, type: "Colorless", rarity: "Rare", setName: "POP Series 5", artist: "Kazuyuki Kano" },
  // Hoenn
  { setId: "dp4", num: "1", name: "Blaziken", hp: 130, type: "Fire", rarity: "Rare", setName: "Great Encounters", artist: "Kagemaru Himeno" },
  { setId: "pop1", num: "4", name: "Sceptile", hp: 110, type: "Grass", rarity: "Rare", setName: "POP Series 1", artist: "Masakazu Fukuda" },
  { setId: "pop1", num: "5", name: "Swampert", hp: 120, type: "Water", rarity: "Rare", setName: "POP Series 1", artist: "Masakazu Fukuda" },
  { setId: "pop4", num: "6", name: "Combusken", hp: 80, type: "Fire", rarity: "Uncommon", setName: "POP Series 4", artist: "Mitsuhiro Arita" },
  { setId: "ex9", num: "4", name: "Gardevoir", hp: 100, type: "Psychic", rarity: "Rare", setName: "Emerald", artist: "Atsuko Nishida" },
  { setId: "pop1", num: "2", name: "Metagross", hp: 100, type: "Metal", rarity: "Rare", setName: "POP Series 1", artist: "Ken Sugimori" },
  { setId: "pl4", num: "8", name: "Salamence", hp: 140, type: "Colorless", rarity: "Rare", setName: "Arceus", artist: "Kagemaru Himeno" },
  { setId: "pop1", num: "3", name: "Rayquaza", hp: 120, type: "Colorless", rarity: "Rare", setName: "POP Series 1", artist: "Aya Kusube" },
  { setId: "cel25", num: "3", name: "Kyogre", hp: 130, type: "Water", rarity: "Rare", setName: "Celebrations", artist: "Akira Komayama" },
  { setId: "ex9", num: "5", name: "Groudon", hp: 120, type: "Fighting", rarity: "Rare", setName: "Emerald", artist: "Kouki Saitou" },
  { setId: "pop4", num: "3", name: "Flygon", hp: 120, type: "Fighting", rarity: "Rare", setName: "POP Series 4", artist: "Kouki Saitou" },
  { setId: "ex3", num: "1", name: "Absol", hp: 70, type: "Darkness", rarity: "Rare", setName: "Dragon", artist: "Naoyo Kimura" },
  // Sinnoh
  { setId: "bw8", num: "1", name: "Turtwig", hp: 60, type: "Grass", rarity: "Common", setName: "Plasma Storm", artist: "Kouki Saitou" },
  { setId: "bw8", num: "2", name: "Grotle", hp: 90, type: "Grass", rarity: "Uncommon", setName: "Plasma Storm", artist: "Kouki Saitou" },
  { setId: "bw8", num: "3", name: "Torterra", hp: 150, type: "Grass", rarity: "Rare", setName: "Plasma Storm", artist: "Kouki Saitou" },
  { setId: "pop8", num: "12", name: "Chimchar", hp: 50, type: "Fire", rarity: "Common", setName: "POP Series 8", artist: "Kouki Saitou" },
  { setId: "bw8", num: "16", name: "Monferno", hp: 80, type: "Fire", rarity: "Uncommon", setName: "Plasma Storm", artist: "Masakazu Fukuda" },
  { setId: "dp7", num: "3", name: "Infernape", hp: 120, type: "Fire", rarity: "Rare", setName: "Stormfront", artist: "Mitsuhiro Arita" },
  { setId: "pop8", num: "15", name: "Piplup", hp: 60, type: "Water", rarity: "Common", setName: "POP Series 8", artist: "Atsuko Nishida" },
  { setId: "dp7", num: "2", name: "Empoleon", hp: 130, type: "Water", rarity: "Rare", setName: "Stormfront", artist: "Mitsuhiro Arita" },
  { setId: "pop9", num: "1", name: "Garchomp", hp: 130, type: "Colorless", rarity: "Rare", setName: "POP Series 9", artist: "Kagemaru Himeno" },
  { setId: "pop8", num: "3", name: "Luxray", hp: 120, type: "Lightning", rarity: "Rare", setName: "POP Series 8", artist: "Mitsuhiro Arita" },
  { setId: "dp1", num: "1", name: "Dialga", hp: 120, type: "Metal", rarity: "Rare", setName: "Diamond & Pearl", artist: "Nakaoka" },
  { setId: "cel25", num: "4", name: "Palkia", hp: 130, type: "Water", rarity: "Rare", setName: "Celebrations", artist: "5ban Graphics" },
  { setId: "dp6", num: "4", name: "Giratina", hp: 130, type: "Psychic", rarity: "Rare", setName: "Legends Awakened", artist: "Kagemaru Himeno" },
  // Unova
  { setId: "bw1", num: "1", name: "Snivy", hp: 60, type: "Grass", rarity: "Common", setName: "Black & White", artist: "Kagemaru Himeno" },
  { setId: "bw1", num: "2", name: "Servine", hp: 80, type: "Grass", rarity: "Uncommon", setName: "Black & White", artist: "Kagemaru Himeno" },
  { setId: "bw1", num: "5", name: "Serperior", hp: 130, type: "Grass", rarity: "Rare", setName: "Black & White", artist: "Masakazu Fukuda" },
  { setId: "bw1", num: "15", name: "Tepig", hp: 70, type: "Fire", rarity: "Common", setName: "Black & White", artist: "Kouki Saitou" },
  { setId: "bw1", num: "17", name: "Pignite", hp: 100, type: "Fire", rarity: "Uncommon", setName: "Black & White", artist: "Kouki Saitou" },
  { setId: "bw1", num: "19", name: "Emboar", hp: 150, type: "Fire", rarity: "Rare", setName: "Black & White", artist: "Kouki Saitou" },
  { setId: "bw1", num: "27", name: "Oshawott", hp: 60, type: "Water", rarity: "Common", setName: "Black & White", artist: "Masakazu Fukuda" },
  { setId: "bw1", num: "28", name: "Dewott", hp: 80, type: "Water", rarity: "Uncommon", setName: "Black & White", artist: "Masakazu Fukuda" },
  { setId: "bw1", num: "32", name: "Samurott", hp: 140, type: "Water", rarity: "Rare", setName: "Black & White", artist: "Masakazu Fukuda" },
  { setId: "sm4", num: "62", name: "Hydreigon", hp: 160, type: "Darkness", rarity: "Rare", setName: "Crimson Invasion", artist: "Anesaki Dynamic" },
  { setId: "sm2", num: "13", name: "Chandelure", hp: 140, type: "Psychic", rarity: "Rare", setName: "Guardians Rising", artist: "Kouki Saitou" },
  { setId: "dv1", num: "16", name: "Haxorus", hp: 140, type: "Dragon", rarity: "Rare", setName: "Dragon Vault", artist: "5ban Graphics" },
  { setId: "bw10", num: "13", name: "Volcarona", hp: 110, type: "Fire", rarity: "Rare", setName: "Plasma Blast", artist: "Shin Nagasawa" },
  { setId: "cel25", num: "2", name: "Reshiram", hp: 130, type: "Fire", rarity: "Rare", setName: "Celebrations", artist: "Aya Kusube" },
  { setId: "cel25", num: "10", name: "Zekrom", hp: 130, type: "Lightning", rarity: "Rare", setName: "Celebrations", artist: "5ban Graphics" },
  // Kalos
  { setId: "xy1", num: "12", name: "Chespin", hp: 60, type: "Grass", rarity: "Common", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "13", name: "Quilladin", hp: 90, type: "Grass", rarity: "Uncommon", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "14", name: "Chesnaught", hp: 160, type: "Grass", rarity: "Rare", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "24", name: "Fennekin", hp: 60, type: "Fire", rarity: "Common", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "25", name: "Braixen", hp: 80, type: "Fire", rarity: "Uncommon", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "26", name: "Delphox", hp: 140, type: "Fire", rarity: "Rare", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "38", name: "Froakie", hp: 60, type: "Water", rarity: "Common", setName: "XY", artist: "5ban Graphics" },
  { setId: "xy1", num: "39", name: "Frogadier", hp: 80, type: "Water", rarity: "Uncommon", setName: "XY", artist: "5ban Graphics" },
  { setId: "det1", num: "9", name: "Greninja", hp: 130, type: "Water", rarity: "Rare", setName: "Detective Pikachu", artist: "MPC Film" },
  { setId: "xy4", num: "10", name: "Talonflame", hp: 130, type: "Fire", rarity: "Rare", setName: "Phantom Forces", artist: "Mitsuhiro Arita" },
  { setId: "cel25", num: "12", name: "Xerneas", hp: 130, type: "Fairy", rarity: "Rare", setName: "Celebrations", artist: "Akira Komayama" },
  { setId: "cel25", num: "19", name: "Yveltal", hp: 130, type: "Darkness", rarity: "Rare", setName: "Celebrations", artist: "TOKIYA" },
  // Alola
  { setId: "sm1", num: "9", name: "Rowlet", hp: 50, type: "Grass", rarity: "Common", setName: "Sun & Moon", artist: "Mizue" },
  { setId: "sm1", num: "10", name: "Dartrix", hp: 80, type: "Grass", rarity: "Uncommon", setName: "Sun & Moon", artist: "Mizue" },
  { setId: "sm1", num: "11", name: "Decidueye", hp: 140, type: "Grass", rarity: "Rare", setName: "Sun & Moon", artist: "Mizue" },
  { setId: "sm1", num: "24", name: "Litten", hp: 60, type: "Fire", rarity: "Common", setName: "Sun & Moon", artist: "Kagemaru Himeno" },
  { setId: "sm1", num: "25", name: "Torracat", hp: 90, type: "Fire", rarity: "Uncommon", setName: "Sun & Moon", artist: "Kagemaru Himeno" },
  { setId: "sm1", num: "26", name: "Incineroar", hp: 160, type: "Fire", rarity: "Rare", setName: "Sun & Moon", artist: "Kagemaru Himeno" },
  { setId: "sm1", num: "39", name: "Popplio", hp: 60, type: "Water", rarity: "Common", setName: "Sun & Moon", artist: "Kouki Saitou" },
  { setId: "sm1", num: "40", name: "Brionne", hp: 90, type: "Water", rarity: "Uncommon", setName: "Sun & Moon", artist: "Kouki Saitou" },
  { setId: "sm1", num: "41", name: "Primarina", hp: 150, type: "Water", rarity: "Rare", setName: "Sun & Moon", artist: "Kouki Saitou" },
  { setId: "swsh3", num: "52", name: "Toxapex", hp: 120, type: "Water", rarity: "Uncommon", setName: "Darkness Ablaze", artist: "Ryota Murayama" },
  { setId: "sm4", num: "77", name: "Kommo-o", hp: 160, type: "Dragon", rarity: "Rare", setName: "Crimson Invasion", artist: "Shin Nagasawa" },
  { setId: "swsh3", num: "61", name: "Tapu Koko", hp: 120, type: "Lightning", rarity: "Rare", setName: "Darkness Ablaze", artist: "Hasuno" },
  { setId: "cel25", num: "21", name: "Solgaleo", hp: 170, type: "Metal", rarity: "Rare", setName: "Celebrations", artist: "Kouki Saitou" },
  { setId: "sm3", num: "58", name: "Mimikyu", hp: 70, type: "Psychic", rarity: "Rare", setName: "Burning Shadows", artist: "Mizue" },
  // Galar
  { setId: "swsh1", num: "10", name: "Grookey", hp: 60, type: "Grass", rarity: "Common", setName: "Sword & Shield", artist: "kirikori" },
  { setId: "swsh1", num: "12", name: "Thwackey", hp: 90, type: "Grass", rarity: "Uncommon", setName: "Sword & Shield", artist: "kirikori" },
  { setId: "swsh1", num: "14", name: "Rillaboom", hp: 170, type: "Grass", rarity: "Rare", setName: "Sword & Shield", artist: "Anesaki Dynamic" },
  { setId: "swsh1", num: "30", name: "Scorbunny", hp: 60, type: "Fire", rarity: "Common", setName: "Sword & Shield", artist: "kirikori" },
  { setId: "swsh1", num: "31", name: "Raboot", hp: 90, type: "Fire", rarity: "Uncommon", setName: "Sword & Shield", artist: "kirikori" },
  { setId: "swsh1", num: "32", name: "Cinderace", hp: 140, type: "Fire", rarity: "Rare", setName: "Sword & Shield", artist: "Kouki Saitou" },
  { setId: "swsh1", num: "55", name: "Sobble", hp: 60, type: "Water", rarity: "Common", setName: "Sword & Shield", artist: "Mizue" },
  { setId: "swsh1", num: "56", name: "Drizzile", hp: 90, type: "Water", rarity: "Uncommon", setName: "Sword & Shield", artist: "Mizue" },
  { setId: "swsh1", num: "58", name: "Inteleon", hp: 150, type: "Water", rarity: "Rare", setName: "Sword & Shield", artist: "Akira Komayama" },
  { setId: "swsh1", num: "135", name: "Corviknight", hp: 140, type: "Metal", rarity: "Rare", setName: "Sword & Shield", artist: "kawayoo" },
  { setId: "swsh12", num: "89", name: "Dragapult", hp: 150, type: "Psychic", rarity: "Rare", setName: "Silver Tempest", artist: "sowsow" },
  // Paldea extras
  { setId: "sv2", num: "41", name: "Armarouge", hp: 140, type: "Fire", rarity: "Rare", setName: "Paldea Evolved", artist: "AKIRA EGAWA" },
  { setId: "sv3", num: "36", name: "Ceruledge", hp: 140, type: "Fire", rarity: "Rare", setName: "Obsidian Flames", artist: "GIDORA" },
  { setId: "xy1", num: "64", name: "Hawlucha", hp: 80, type: "Fighting", rarity: "Rare", setName: "XY", artist: "5ban Graphics" },
  { setId: "sm4", num: "91", name: "Zoroark", hp: 120, type: "Darkness", rarity: "Rare", setName: "Crimson Invasion", artist: "kawayoo" },
  { setId: "sm1", num: "76", name: "Lycanroc", hp: 110, type: "Fighting", rarity: "Rare", setName: "Sun & Moon", artist: "Masakazu Fukuda" },
  { setId: "sm1", num: "52", name: "Vikavolt", hp: 140, type: "Lightning", rarity: "Rare", setName: "Sun & Moon", artist: "Hitoshi Ariga" },
  { setId: "swsh1", num: "138", name: "Zacian", hp: 120, type: "Metal", rarity: "Rare", setName: "Sword & Shield", artist: "Kouki Saitou" },
  { setId: "swsh1", num: "139", name: "Zamazenta", hp: 130, type: "Metal", rarity: "Rare", setName: "Sword & Shield", artist: "Kouki Saitou" },
  { setId: "sv3pt5", num: "57", name: "Primeape", hp: 110, type: "Fighting", rarity: "Uncommon", setName: "151", artist: "GOSSAN" },
  { setId: "sv4", num: "109", name: "Annihilape", hp: 140, type: "Fighting", rarity: "Rare", setName: "Paradox Rift", artist: "Anesaki Dynamic" },
  { setId: "sv4", num: "134", name: "Kingambit", hp: 160, type: "Darkness", rarity: "Rare", setName: "Paradox Rift", artist: "Anesaki Dynamic" },
  { setId: "ex6", num: "28", name: "Treecko", hp: 50, type: "Grass", rarity: "Common", setName: "FireRed & LeafGreen", artist: "Atsuko Nishida" },
  { setId: "ex6", num: "32", name: "Torchic", hp: 50, type: "Fire", rarity: "Common", setName: "FireRed & LeafGreen", artist: "Mitsuhiro Arita" },
  { setId: "ex6", num: "33", name: "Mudkip", hp: 50, type: "Water", rarity: "Common", setName: "FireRed & LeafGreen", artist: "Atsuko Nishida" },
  { setId: "dp2", num: "33", name: "Weavile", hp: 80, type: "Darkness", rarity: "Rare", setName: "Mysterious Treasures", artist: "Kagemaru Himeno" },
];

function buildCatalog() {
  const cards = [];
  const seenNames = new Set();

  for (const row of SV151) {
    if (Array.isArray(row)) {
      const [num, name, hp, type, rarity] = row;
      const key = name.replace(/\s+(ex|V|VMAX|VSTAR)$/i, "").toLowerCase();
      if (seenNames.has(key)) continue;
      seenNames.add(key);

      const images = img("sv3pt5", num);
      const dexNumber = lookupDexNumber(name, String(num).padStart(3, "0"), "151") || num;
      cards.push({
        externalId: `sv3pt5-${String(num).padStart(3, "0")}`,
        name,
        hp,
        types: [type],
        rarity,
        dexNumber,
        ...images,
        setName: "151",
        setTotal: "165",
        number: String(num).padStart(3, "0"),
        marketPrice: priceFor(rarity),
        artist: "Various",
      });
    }
  }

  const additionalLists = [PREMIUM_FULLART, EXTRA_CARDS, REGION_CARDS];
  for (const list of additionalLists) {
    for (const c of list) {
      if (!c.setId) continue;
      // Allow premium/variant versions of the same species
      const key = `${c.name.toLowerCase()}-${c.setId}-${c.num}`;
      const images = img(c.setId, c.num);
      const dexNumber = lookupDexNumber(c.name, c.num, c.setName);
      cards.push({
        externalId: `${c.setId}-${c.num}`,
        name: c.name,
        hp: c.hp,
        types: [c.type],
        rarity: c.rarity,
        dexNumber,
        ...images,
        setName: c.setName,
        setTotal: c.setTotal || "122",
        number: String(c.num).padStart(3, "0"),
        marketPrice: priceFor(c.rarity),
        artist: c.artist,
      });
    }
  }

  return cards.map(enrichCard).filter((card, i, arr) =>
    arr.findIndex((c) => c.externalId === card.externalId) === i
  );
}

module.exports = { buildCatalog, priceFor };
